### PR TITLE
Added more silliness: ransomize

### PR DESCRIPTION
**Pull request by quephird**
Hey Misty...

Sorry if I'm taking this too far but I wrote another function. :3

I'm definitely getting more exposure to Python this way!

danielle

### CODE REVIEW

**Comment by mistydemeo** [comment]
ee thank you :D Merged!

**Comment by mistydemeo** [comment]
I made a tweak in a followup commit to fix this in Python 3. A really weird change they made is that `map()` returns an iterator instead of a list, which means that `len()` doesn't work on the result of a `map()` call, and neither does square bracket indexing. I switched one of the constants to a list comprehension, which does always return a list.

Thanks again! :D

**Comment by quephird** [comment]
^_^ I do hope this is all in alignment with the intent of your project, by the way. :3

**Comment by mistydemeo** [comment]
Yes, definitely :D

**Pull request closed without merging**
